### ISSUE TITLE
Error when install pip package - setuptools

### ISSUE THREAD

**Issue by Divkix** [bitnami/bitnami-docker-python#13]
**Description**

Cannot build the image either with 3.9.2 or 3.9.2-prod

**Steps to reproduce the issue:**

1. Start the build Process

**Describe the results you received:**

Build fails

The image should have been built properly.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.113GiB
 Name: docker-desktop
 ID: DZ4J:ISHE:FMP7:3RL3:75Y4:FYE5:OMML:U3X4:HL6E:CGPR:2YXN:DUKL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output Error
```
> [7/7] RUN make install:
#11 4.309 Requirement already satisfied: pip in /opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg (20.3.4)
#11 5.110 Collecting pip
#11 5.548   Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
#11 5.988 Requirement already satisfied: setuptools in /opt/bitnami/python/lib/python3.9/site-packages/setuptools-46.4.0-py3.9.egg (46.4.0)
#11 8.229 Collecting setuptools
#11 8.285   Downloading setuptools-54.1.1-py3-none-any.whl (784 kB)
#11 8.593 Installing collected packages: setuptools, pip
#11 8.593   Attempting uninstall: setuptools
#11 8.594     Found existing installation: setuptools 46.4.0
#11 8.598     Uninstalling setuptools-46.4.0:
#11 9.001       Successfully uninstalled setuptools-46.4.0
#11 10.26   Attempting uninstall: pip
#11 10.26     Found existing installation: pip 20.3.4
#11 10.26     Uninstalling pip-20.3.4:
#11 11.13       Successfully uninstalled pip-20.3.4
#11 13.58 Successfully installed pip-21.0.1 setuptools-54.1.1
#11 13.60 Traceback (most recent call last):
#11 13.60   File "/opt/bitnami/python/bin/pip3", line 11, in <module>
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_internal/cli/main.py", line 75, in main
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_internal/cli/base_command.py", line 116, in main
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_internal/cli/base_command.py", line 260, in _main
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_internal/cli/req_command.py", line 147, in handle_pip_version_check
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_internal/cli/req_command.py", line 88, in _build_session
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_internal/network/session.py", line 248, in __init__
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_internal/network/session.py", line 158, in user_agent
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_internal/utils/misc.py", line 668, in get_installed_version
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_vendor/pkg_resources/__init__.py", line 1983, in find_eggs_in_zip
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_vendor/pkg_resources/__init__.py", line 1854, in _has
#11 13.60   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_vendor/pkg_resources/__init__.py", line 1731, in zipinfo
#11 13.61   File "/opt/bitnami/python/lib/python3.9/site-packages/pip-20.3.4-py3.9.egg/pip/_vendor/pkg_resources/__init__.py", line 1688, in load
#11 13.61 FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/python/lib/python3.9/site-packages/setuptools-46.4.0-py3.9.egg'
#11 13.71 make: *** [Makefile:5: install] Error 1
------
executor failed running [/bin/sh -c make install]: exit code: 2
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Physical Hardware

**Comment by migruiz4** [comment]
Hi @Divkix,

I think your issue could be related to this: https://github.com/bitnami/bitnami-docker-python/issues/3

Running `rm -r /opt/bitnami/python/lib/python3.9/site-packages/setuptools*` before your command should fix the issue.

**Comment by Divkix** [comment]
Hey @migruiz4 ,
Thanks for responding.
I tried as you suggested and now got this error:

```
=> [6/8] RUN rm -r /opt/bitnami/python/lib/python3.9/site-packages/setuptools*                                                                                                                             2.6s
 => ERROR [7/8] RUN pip3 install -U distribute                                                                                                                                                              2.3s
------
 > [7/8] RUN pip3 install -U distribute:
#10 1.678 Traceback (most recent call last):
#10 1.679   File "/opt/bitnami/python/bin/pip3", line 6, in <module>
#10 1.680     from pkg_resources import load_entry_point
#10 1.680 ModuleNotFoundError: No module named 'pkg_resources'
------
executor failed running [/bin/sh -c pip3 install -U distribute]: exit code: 1
```

I can't use pip install now because of it

**Comment by Divkix** [comment]
> #Upgrade pip
> RUN pip3 install --no-cache-dir -U pip
> #The upgrade setuptools 
> RUN rm -r /opt/bitnami/python/lib/python3.9/site-packages/setuptools*
> RUN pip3 install --no-cache-dir -U setuptools

Hey @migruiz4,
Thanks a lot, that fixed my issue.
Although I tried updating `pip` using my config, it looks like I had to manually run that.

Thanks for all the help!!

**Comment by migruiz4** [comment]
I'm glad it worked!

> Although I tried updating pip using my config, it looks like I had to manually run that.
Yes, attempting to upgrade both `pip` and `setuptools` in the same command would cause issues, the only solution that worked in my tests was the one I shared.
First upgrade pip, then apply the fix for setuptools and upgrade it.
