### ISSUE TITLE
C compiler needed

### ISSUE THREAD

**Issue by jantonacci** [bitnami/bitnami-docker-python#15]
**Description**

Need a C compiler to build uWSGI on image `bitnami/python:3.9`

**Steps to reproduce the issue:**

1. pip install uwsgi

**Describe the results you received:**
```
    Running setup.py install for uwsgi: started
    Running setup.py install for uwsgi: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/bitnami/python/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x4mqvhgw/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bitnami/python/include/python3.9/uwsgi
         cwd: /tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/
    Complete output (28 lines):
    /opt/bitnami/python/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
      warnings.warn(msg)
    running install
    using profile: buildconf/default.ini
    detected include path: ['/usr/include', '/usr/local/include']
    Traceback (most recent call last):
      File "/tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/uwsgiconfig.py", line 747, in __init__
        gcc_version_components = gcc_version.split('.')
    AttributeError: 'NoneType' object has no attribute 'split'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/setup.py", line 117, in <module>
        setup(
      File "/opt/bitnami/python/lib/python3.9/site-packages/setuptools-46.4.0-py3.9.egg/setuptools/__init__.py", line 144, in setup
      File "/opt/bitnami/python/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/bitnami/python/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/bitnami/python/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/setup.py", line 77, in run
        conf = uc.uConf(get_profile())
      File "/tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/uwsgiconfig.py", line 755, in __init__
        raise Exception("you need a C compiler to build uWSGI")
    Exception: you need a C compiler to build uWSGI
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/bitnami/python/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bao4o026/uwsgi_69c985f6ef994ab9b3518a0e0f133393/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x4mqvhgw/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bitnami/python/include/python3.9/uwsgi Check the logs for full command output.
```

** Describe what you expect to happen **
```
Collecting uwsgi
  Using cached uWSGI-2.0.19.1.tar.gz (803 kB)
Building wheels for collected packages: uwsgi
  Building wheel for uwsgi (setup.py) ... done
  Created wheel for uwsgi: filename=uWSGI-2.0.19.1-cp39-cp39-linux_x86_64.whl size=515058 sha256=19bda86437bdeca5dbdf80e21420e7034d253cc3dd93caaf7a75ab96b7aac740
  Stored in directory: /home/user/.cache/pip/wheels/17/66/cf/112237fefe0b8011e4a481305ba799b696ece8590219bd527f
Successfully built uwsgi
Installing collected packages: uwsgi
Successfully installed uwsgi-2.0.19.1
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:33:55 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:32:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.15.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.49GiB
 Name: glrun04
 ID: V7XT:UFIX:E5ZH:GPGZ:3HAR:GH2V:RBPM:Y33W:VFMG:BZR2:YYS3:RNLY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker-registry-mirrors.example.com/
 Live Restore Enabled: false
```

**Comment by migruiz4** [comment]
Hi @jantonacci,

The `bitnami/python:3.9` does not include the C compiler to keep the image lightweigth and to minimize potential vulnerabilities. 

This is usually not a problem, as most of the Python modules are also distributed as Wheels. But in some cases, modules such as `uWSGI` do not provide wheels because of the project complexity.

As a workaround, I would suggest one of the following solutions:
- Build a custom image:
```Dockerfile
FROM bitnami/python:3.9

RUN install_packages gcc libc6-dev
RUN pip install uwsgi
```
- Build the uWSGI wheel and mount it as a volume:
    - Create a script to build the wheel
    ```
    #Install dependencies
    install_packages gcc libc6-dev
    pip install wheel
    
    #Download uWSGI
    curl -O https://files.pythonhosted.org/packages/c7/75/45234f7b441c59b1eefd31ba3d1041a7e3c89602af24488e2a22e11e7259/uWSGI-2.0.19.1.tar.gz
    tar -xzf uWSGI-2.0.19.1.tar.gz
    
    #Build wheel
    python setup.py bdist_wheel
    
    #Export wheel
    mv dist/uWSGI-*.whl /out/
    ```
    - Build the wheel
    ```
    docker run --rm -v /path/to/build_uwsgi.sh:/build.sh -v /path/to/wheels:/out -it bitnami/python:3.9 bash /build.sh
    ```
    - Install the wheel using `pip install /out/uWSGI-2.0.19.1-cp39-cp39-linux_x86_64.whl`. For example:
    ```console
    $ docker run --rm -v /path/to/wheels:/out -it bitnami/python:3.9 pip install /out/uWSGI-2.0.19.1-cp39-cp39-linux_x86_64.whl
    Processing /out/uWSGI-2.0.19.1-cp39-cp39-linux_x86_64.whl
    Installing collected packages: uWSGI
    Successfully installed uWSGI-2.0.19.1
    ```
- Use `pyuwsgi` instead (https://pypi.org/project/pyuwsgi/)

We don't see the C compiler requested too frequently, but if the community interest grows, we may evaluate adding it to the python image by default.

**Comment by jantonacci** [comment]
Hi @migruiz4,

This all makes sense and I expected that was the case.  Adding `install_packages gcc libc6-dev` to our pipelines is a trivial change and solves the issue nicely.  Thanks for the speedy, detailed response with multiple solutions plus your time and expertise.

Closed as resolved! 👍
