### ISSUE TITLE
setupools cannot be upgraded

### ISSUE THREAD

**Issue by naringas** [bitnami/bitnami-docker-python#5]
**Description**

setupools cannot be upgraded (dupe of closed issue #3)

**Steps to reproduce the issue:**

1. run `docker run bitnami/python:3.7 pip install -U setuptools`
2. Error

**Describe the results you received:**

```
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/e7/16/da8cb8046149d50940c6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl (573kB)
Installing collected packages: setuptools
  Found existing installation: setuptools 23.0.0
    Uninstalling setuptools-23.0.0:
      Successfully uninstalled setuptools-23.0.0
Successfully installed setuptools
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/bitnami/python/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/basecommand.py", line 246, in main
    pip_version_check(session)
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/utils/__init__.py", line 848, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/_vendor/pkg_resources/__init__.py", line 626, in __init__
    self.add_entry(entry)
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/_vendor/pkg_resources/__init__.py", line 682, in add_entry
    for dist in find_distributions(entry, True):
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2080, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1610, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1968, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1848, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/opt/bitnami/python/lib/python3.7/site-packages/pip-8.1.1-py3.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1788, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/python/lib/python3.7/site-packages/setuptools-23.0.0-py3.7.egg'
```

Interestingly before the errors the output says `Successfully uninstalled setuptools-23.0.0` but the wheel it downloads `setuptools-40.6.2-py2.py3-none-any.whl`

**Describe the results you expected:**

setuptools 40.6.2 is installed without error

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 32
 Running: 0
 Paused: 0
 Stopped: 32
Images: 447
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.706GiB
Name: linuxkit-025000000001
ID: IQXO:ZUG7:3A6B:ETIX:GWCV:GIR2:WXTJ:IXYW:MZF5:667N:HK3W:6VCY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 53
 System Time: 2018-12-07T17:22:38.8174148Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by andresbono** [comment]
Hi @naringas, does the solution provided in https://github.com/bitnami/bitnami-docker-python/issues/3#issue-359122570 work for you?

```
rm -r /opt/bitnami/python/lib/python3.7/site-packages/setuptools*
pip install --no-cache-dir -U setuptools
```

**Comment by naringas** [comment]
it works, but I consider it a workaround not a proper solution; I hope a better solution can be found.

I was looking through the source Dockerfile and I noticed it install python from a custom tarball?
I couldn't debug any further because I don't know where this tarball comes from. But it seems to me that this tarball is the culprit??

thanks.

**Comment by andresbono** [comment]
Hi @naringas, yes, it is kind of a workaround that we hope it's useful in the meantime we check which version of the python tools should be included in the tarball that you mention.

We will update this issue as soon as we have more information.

**Comment by naringas** [comment]
maybe do a proper `.deb` package and simply use `install_packages` ?

**Comment by andresbono** [comment]
Hi @naringas, we will update the python tools in the tarball maintaining compatibility between them.

We'll keep you in the loop.

**Comment by jotamartos** [comment]
Closing this issue as our latest Python image contains an updated version of setuptools (41.2.0)
